[package]
name = "zip-rust"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
lto = true

[dependencies]
wasm-bindgen = "0.2"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
